Rewrite the mod
GTNewHorizons/ToroHealth pull request #2
Opened 2023-09-18 13:19 UTC by Alexdoru

2023-09-24 19:03 UTC, glowredman requested changes

2023-09-24 19:03 UTC, glowredman commented on gradle.properties
> +generateGradleTokenClass = net.torocraft.Tags
I think you want `net.torocraft.torohealthmod.Tags`

2023-09-24 19:03 UTC, glowredman commented on gradle.properties
> +gradleTokenModId = GRADLETOKEN_MODID
Don't tokenize the modid please.

2023-09-24 19:03 UTC, glowredman commented on gradle.properties
>  replaceGradleTokenInFile = ToroHealthMod.java
You use `generateGradleTokenClass` so clear this one. Also you'd need to reference `Tags.VERSION` in the `@Mod` annotation on the main mod class.

2023-09-24 19:03 UTC, glowredman commented on gradle.properties
> +mixinsPackage = mixin.mixins
See https://github.com/GTNewHorizons/Hodgepodge/pull/247

2023-09-24 19:03 UTC, glowredman commented on src/main/java/net/torocraft/torohealthmod/client/configuration/ConfigurationHandler.java
> +@SideOnly(Side.CLIENT)
Don't use `@SideOnly`

2023-09-24 19:03 UTC, glowredman commented on src/main/java/net/torocraft/torohealthmod/client/event/ToroHealthEventHandler.java
> +@SideOnly(Side.CLIENT)
Don't use `@SideOnly`.

2023-09-24 19:03 UTC, glowredman commented on src/main/java/net/torocraft/torohealthmod/client/particle/DamageParticles.java
> +@SideOnly(Side.CLIENT)
Don't use `@SideOnly`.

2023-09-24 20:23 UTC, Alexdoru commented on gradle.properties
> +gradleTokenModId = GRADLETOKEN_MODID
why ?

2023-09-25 18:57 UTC, Alexdoru commented on gradle.properties
> +mixinsPackage = mixin.mixins
no

2023-09-25 19:50 UTC, glowredman approved these changes

2023-09-25 19:51 UTC, merged